Add IPAddr#to_unmasked_string
ruby/ipaddr pull request #26
Opened 2020-09-01 15:29 UTC by composerinteralia

Prior to this commit there was no way to retrieve the unmasked address
for an `IPAddr`. For example, given the `IPAddr` below there is no
method or instance variable that would return `"1.2.3.4"`.

```rb
IPAddr.new("1.2.3.4/8")
```

This poses a problem for Rails in supporting the PostgreSQL inet type.
Rails uses `IPAddr` for both the cidr and inet types, but at the moment
cannot fully support the inet type, which "accepts values with nonzero
bits to the right of the netmask". This came up originally in
https://github.com/rails/rails/issues/14857, and more recently in
https://github.com/rails/rails/issues/40138. The change in this commit
would allow us to support the inet type without moving to another
library.

This commit holds onto the address before the mask is applied, in a new
instance variable `@unmasked_addr`. It then exposes this via
`to_unmasked_string`.

This was originally implemented back in
https://github.com/ruby/ruby/pull/599, but it got stale and was
eventually closed. There are also a few differences with that PR:

- That PR set up the instance variable inside of `mask!`, which meant
  that the new method was broken in the case of an `IPAddr` with no
  mask.
- That PR introduced a method that returned a `to_s`-like value, whereas
  this one returns a `to_string`-like value. This seems to fit better
  with the method name. And if folks need to get the `to_s` value they
  can always wrap the return value in another `IPAddr` and call `to_s`
  on that.
- As a result of the above, this version doesn't need to change the
  signature of `to_s`

2020-09-14 09:35 UTC, CvX requested changes
This breaks when used on an instance initiated with a non-string:

```rb
a = IPAddr.new(2130706433, Socket::AF_INET)
a.to_s == "127.0.0.1"
a.to_unmasked_string
# NoMethodError: undefined method `>>' for nil:NilClass
```

I've submitted a PR to your fork to amend this: https://github.com/composerinteralia/ipaddr/pull/1

2020-09-14 16:57 UTC, composerinteralia commented
Nice catch @CvX. While reviewing your changes I also spotted some other cases where we call `.clone.set`. I kept your test case and added you as a co-author, but moved the line to set `@unmasked_addr` into the `set` method.

2020-09-14 18:19 UTC, CvX commented
> spotted some other cases where we call `.clone.set`

Good one! LGTM 🙂 :shipit:

2020-09-15 02:54 UTC, ioquatix commented
Do you think `to_unmasked_string` is the right name for this?

I agree with the functionality.

Just want to make sure this is the right name.

Is this a `to_` conversion or a property of the address? e.g. `address.unmasked.to_s` might make more sense?

How does this work with IPv6?

2020-09-15 04:19 UTC, composerinteralia commented
@ioquatix thanks for the review. Yeah, I think your suggestion of `unmasked` instead of `to_unmasked_string` is better. I updated the PR to take that suggestion.

> How does this work with IPv6?

I have a couple IPv6 test cases. Are there additional cases that I am missing?

2020-09-16 20:48 UTC, ioquatix approved these changes

2020-09-16 20:48 UTC, ioquatix commented
LGTM.

2020-09-16 23:28 UTC, hsbt commented
The maintainer of ipaddr is @knu

2021-07-22 10:59 UTC, Sebbb commented
Hello,

I have a question about this.

It actually took me quite a while to figure out what's wrong, as also Postgres' inet data type is mapped to IPAddr.

```
> IPAddr.new('1.2.3.4/24').to_s
=> "1.2.3.0"
```

Athough it's a behavior change, normally I would expect IPAddr to keep the host bits. So wouldn't it make sense to adjust the code, that the example above returns '1.2.3.4'? and to introduce a function that returns the network address (discards the host bits)?

```
> IPAddr.new('1.2.3.4/24').to_s
=> "1.2.3.4"
> IPAddr.new('1.2.3.4/24').network_address.to_s
=> "1.2.3.0"
```

Seb

2021-11-21 21:39 UTC, ioquatix commented
@composerinteralia do you have some time to check the above feedback? It would be awesome to merge this in time for Ruby 3.1

cc @knu

2021-11-22 01:37 UTC, composerinteralia commented
I’m on vacation for the next two weeks away from a computer, but I can take a look when I get back. Anyone is also welcome to take over in the meantime.

2021-12-03 17:19 UTC, composerinteralia commented
> Athough it's a behavior change, normally I would expect IPAddr to keep the host bits. So wouldn't it make sense to adjust the code, that the example above returns '1.2.3.4'

I can revise this PR if that's the direction folks want to go, but it's a potentially disruptive breaking change for anyone relying on the existing behavior (I believe we're relying on it for the cidr type in Rails, for example). I assume that would need to be a major release, and ideally there would be some sort of deprecation cycle.

> If the goal is to not break the (strange) behavior, maybe an unmasked function that again returns an IPAddr object (and not a string) would make sense:

I believe that's what this PR does. (Although it's been a while, so please correct me if I am mistaken.)

2025-08-05 11:38 UTC, closed without merging